repos:
-   repo: local
    hooks:
    - id: cargo-build
      name: cargo-build
      entry: cargo build --release --workspace
      language: system
      pass_filenames: false
    - id: cargo-test
      name: cargo-test
      entry: cargo test --release --workspace
      language: system
      pass_filenames: false
    - id: cargo-clippy
      name: cargo-clippy
      entry: cargo clippy --workspace --release --all-targets --all-features -- -D warnings
      language: system
      pass_filenames: false
        
