# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x04game\"\x07\n\x05\x45mpty\"$\n\x0cInputRequest\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01z\x18\x02 \x01(\x02\";\n\nPlayerView\x12\"\n\x0bsurrounding\x18\x01 \x03(\x0b\x32\r.game.Terrain\x12\t\n\x01y\x18\x02 \x01(\x02\"\'\n\x07Terrain\x12\x0e\n\x06height\x18\x01 \x01(\x02\x12\x0c\n\x04kind\x18\x02 \x01(\x05\"\'\n\x05Score\x12\x0f\n\x07timings\x18\x01 \x03(\x03\x12\r\n\x05total\x18\x02 \x01(\x05\x32\xce\x01\n\x0bMainService\x12\"\n\x06health\x12\x0b.game.Empty\x1a\x0b.game.Empty\x12)\n\x08getState\x12\x0b.game.Empty\x1a\x10.game.PlayerView\x12(\n\x05input\x12\x12.game.InputRequest\x1a\x0b.game.Empty\x12 \n\x04kill\x12\x0b.game.Empty\x1a\x0b.game.Empty\x12$\n\x08getScore\x12\x0b.game.Empty\x1a\x0b.game.Scoreb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=20
  _EMPTY._serialized_end=27
  _INPUTREQUEST._serialized_start=29
  _INPUTREQUEST._serialized_end=65
  _PLAYERVIEW._serialized_start=67
  _PLAYERVIEW._serialized_end=126
  _TERRAIN._serialized_start=128
  _TERRAIN._serialized_end=167
  _SCORE._serialized_start=169
  _SCORE._serialized_end=208
  _MAINSERVICE._serialized_start=211
  _MAINSERVICE._serialized_end=417
# @@protoc_insertion_point(module_scope)
